/**
 * PDF Export Utilities
 * Functions for generating beautiful PDF reports from stream analytics data
 */

import jsPDF from "jspdf";
import autoTable, { UserOptions } from "jspdf-autotable";
import { StreamExportData } from "./stream-export";
import { formatDate } from "./csv-export";

/**
 * PDF styling configuration
 */
const PDF_CONFIG = {
  primaryColor: [16, 185, 129] as [number, number, number], // #10B981 - Green
  secondaryColor: [15, 23, 42] as [number, number, number], // Dark background
  textColor: [30, 41, 59] as [number, number, number], // Slate
  lightGray: [241, 245, 249] as [number, number, number],
  pageMargin: 20,
  headerHeight: 40,
  footerHeight: 20,
};

/**
 * Add header to PDF page
 */
function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  // Header background
  doc.setFillColor(PDF_CONFIG.primaryColor[0], PDF_CONFIG.primaryColor[1], PDF_CONFIG.primaryColor[2]);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), PDF_CONFIG.headerHeight, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(title, PDF_CONFIG.pageMargin, 25);

  // Subtitle
  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, PDF_CONFIG.pageMargin, 32);
  }

  // Reset text color
  doc.setTextColor(PDF_CONFIG.textColor[0], PDF_CONFIG.textColor[1], PDF_CONFIG.textColor[2]);
}

/**
 * Add footer to PDF page
 */
function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont("helvetica", "normal");
  
  const footerText = `Page ${pageNumber} of ${totalPages} | Generated by Drip - Programmable Payments`;
  const textWidth = doc.getTextWidth(footerText);
  
  doc.text(footerText, pageWidth - textWidth - PDF_CONFIG.pageMargin, pageHeight - 10);
}

/**
 * Add summary statistics section
 */
function addSummarySection(
  doc: jsPDF,
  summaryStats: {
    totalStreams: number;
    activeStreams: number;
    pausedStreams: number;
    completedStreams: number;
    cancelledStreams: number;
    totalDeposits: Record<string, string>;
    totalDistributed: Record<string, string>;
    totalRecipients: number;
  }
) {
  let yPos = PDF_CONFIG.headerHeight + 15;

  // Section title
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PDF_CONFIG.textColor[0], PDF_CONFIG.textColor[1], PDF_CONFIG.textColor[2]);
  doc.text("Summary Statistics", PDF_CONFIG.pageMargin, yPos);
  yPos += 10;

  // Summary boxes
  const boxWidth = 85;
  const boxHeight = 30;
  const spacing = 10;
  const startX = PDF_CONFIG.pageMargin;
  let currentX = startX;

  // Total Streams
  addStatBox(doc, currentX, yPos, boxWidth, boxHeight, "Total Streams", summaryStats.totalStreams.toString());
  currentX += boxWidth + spacing;

  // Active Streams
  addStatBox(doc, currentX, yPos, boxWidth, boxHeight, "Active", summaryStats.activeStreams.toString());
  currentX += boxWidth + spacing;

  // Total Recipients
  addStatBox(doc, currentX, yPos, boxWidth, boxHeight, "Total Recipients", summaryStats.totalRecipients.toString());

  yPos += boxHeight + 15;

  // Token totals
  if (Object.keys(summaryStats.totalDeposits).length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Token Totals", PDF_CONFIG.pageMargin, yPos);
    yPos += 8;

    const tokenData = Object.entries(summaryStats.totalDeposits).map(([token, deposit]) => ({
      Token: token,
      "Total Deposits": deposit,
      "Total Distributed": summaryStats.totalDistributed[token] || "0",
    }));

    autoTable(doc, {
      startY: yPos,
      head: [["Token", "Total Deposits", "Total Distributed"]],
      body: tokenData.map((row) => [row.Token, row["Total Deposits"], row["Total Distributed"]]),
      theme: "striped",
      headStyles: {
        fillColor: PDF_CONFIG.primaryColor as [number, number, number],
        textColor: [255, 255, 255] as [number, number, number],
        fontStyle: "bold",
      },
      styles: {
        fontSize: 9,
      },
      margin: { left: PDF_CONFIG.pageMargin, right: PDF_CONFIG.pageMargin },
    });

    const finalY = (doc as any).lastAutoTable?.finalY;
    yPos = finalY ? finalY + 10 : yPos + 50;
  }

  return yPos;
}

/**
 * Add a statistics box
 */
function addStatBox(doc: jsPDF, x: number, y: number, width: number, height: number, label: string, value: string) {
  // Box background
  doc.setFillColor(PDF_CONFIG.lightGray[0], PDF_CONFIG.lightGray[1], PDF_CONFIG.lightGray[2]);
  doc.roundedRect(x, y, width, height, 3, 3, "F");

  // Border
  doc.setDrawColor(PDF_CONFIG.primaryColor[0], PDF_CONFIG.primaryColor[1], PDF_CONFIG.primaryColor[2]);
  doc.setLineWidth(0.5);
  doc.roundedRect(x, y, width, height, 3, 3, "S");

  // Label
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(label, x + 5, y + 8);

  // Value
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PDF_CONFIG.primaryColor[0], PDF_CONFIG.primaryColor[1], PDF_CONFIG.primaryColor[2]);
  doc.text(value, x + 5, y + 20);
}

/**
 * Add streams summary table
 */
function addStreamsSummaryTable(doc: jsPDF, streamsData: StreamExportData[], startY: number) {
  const tableData = streamsData.map((data) => [
    data.stream.id,
    data.stream.title || "(No title)",
    data.stream.status,
    data.stream.token.symbol,
    data.stream.deposit,
    data.analytics.totalDistributed,
    data.analytics.remainingDeposit,
    data.recipients.length.toString(),
    data.stream.startTime,
  ]);

  autoTable(doc, {
    startY,
    head: [
      [
        "ID",
        "Title",
        "Status",
        "Token",
        "Deposit",
        "Distributed",
        "Remaining",
        "Recipients",
        "Start Date",
      ],
    ],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: PDF_CONFIG.primaryColor as [number, number, number],
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 30 }, // ID
      1: { cellWidth: 60 }, // Title
      2: { cellWidth: 35 }, // Status
      3: { cellWidth: 30 }, // Token
      4: { cellWidth: 40 }, // Deposit
      5: { cellWidth: 40 }, // Distributed
      6: { cellWidth: 40 }, // Remaining
      7: { cellWidth: 30 }, // Recipients
      8: { cellWidth: 50 }, // Start Date
    },
    margin: { left: PDF_CONFIG.pageMargin, right: PDF_CONFIG.pageMargin },
    didDrawPage: (data) => {
      // Add header and footer to each page
      addHeader(doc, "Streams Analytics Report", "Comprehensive stream data and analytics");
      const totalPages = (doc as any).internal.getNumberOfPages();
      addFooter(doc, data.pageNumber, totalPages);
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY;
  return finalY ? finalY + 10 : startY + 50;
}

/**
 * Add detailed stream section
 */
function addStreamDetails(doc: jsPDF, streamData: StreamExportData, startY: number): number {
  let yPos = startY;

  // Check if we need a new page
  if (yPos > doc.internal.pageSize.getHeight() - 100) {
    doc.addPage();
    addHeader(doc, "Streams Analytics Report", "Comprehensive stream data and analytics");
    yPos = PDF_CONFIG.headerHeight + 15;
  }

  // Stream title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PDF_CONFIG.textColor[0], PDF_CONFIG.textColor[1], PDF_CONFIG.textColor[2]);
  doc.text(`Stream #${streamData.stream.id}`, PDF_CONFIG.pageMargin, yPos);
  yPos += 8;

  if (streamData.stream.title) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(streamData.stream.title, PDF_CONFIG.pageMargin, yPos);
    yPos += 10;
  }

  // Stream information table
  const streamInfo = [
    ["Sender", streamData.stream.sender],
    ["Token", `${streamData.stream.token.symbol} (${streamData.stream.token.address})`],
    ["Status", streamData.stream.status],
    ["Start Time", streamData.stream.startTime],
    ["End Time", streamData.stream.endTime],
    ["Contract", streamData.stream.contractAddress],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["Property", "Value"]],
    body: streamInfo,
    theme: "plain",
    headStyles: {
      fillColor: PDF_CONFIG.primaryColor as [number, number, number],
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
    },
    margin: { left: PDF_CONFIG.pageMargin, right: PDF_CONFIG.pageMargin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 10;

  // Analytics table
  const analyticsInfo = [
    ["Total Deposit", streamData.analytics.totalDeposit],
    ["Total Distributed", streamData.analytics.totalDistributed],
    ["Total Available", streamData.analytics.totalAvailable],
    ["Remaining Deposit", streamData.analytics.remainingDeposit],
    ["Duration", streamData.analytics.duration],
    ["Time Elapsed", streamData.analytics.elapsed],
  ];

  if (streamData.analytics.remaining) {
    analyticsInfo.push(["Time Remaining", streamData.analytics.remaining]);
  }

  autoTable(doc, {
    startY: yPos,
    head: [["Metric", "Value"]],
    body: analyticsInfo,
    theme: "plain",
    headStyles: {
      fillColor: PDF_CONFIG.primaryColor as [number, number, number],
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
    },
    margin: { left: PDF_CONFIG.pageMargin, right: PDF_CONFIG.pageMargin },
  });

  yPos = (doc as any).lastAutoTable.finalY + 10;

  // Recipients table
  if (streamData.recipients.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Recipients", PDF_CONFIG.pageMargin, yPos);
    yPos += 8;

    const recipientData = streamData.recipients.map((recipient) => [
      recipient.address,
      recipient.ratePerSecond,
      recipient.totalWithdrawn,
      recipient.currentAvailable,
      recipient.totalReceived,
      recipient.percentageOfDeposit,
      recipient.percentageOfDistributed,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [
        [
          "Address",
          "Rate/Sec",
          "Withdrawn",
          "Available",
          "Total Received",
          "% of Deposit",
          "% of Distributed",
        ],
      ],
      body: recipientData,
      theme: "striped",
      headStyles: {
        fillColor: PDF_CONFIG.primaryColor as [number, number, number],
        textColor: [255, 255, 255] as [number, number, number],
        fontStyle: "bold",
      },
      styles: {
        fontSize: 7,
        cellPadding: 2,
      },
      margin: { left: PDF_CONFIG.pageMargin, right: PDF_CONFIG.pageMargin },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;
  } else {
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("No recipients", PDF_CONFIG.pageMargin, yPos);
    yPos += 10;
  }

  return yPos;
}

/**
 * Generate PDF report for all streams
 */
export function generateStreamsPDF(
  allStreamsData: StreamExportData[],
  summaryStats?: {
    totalStreams: number;
    activeStreams: number;
    pausedStreams: number;
    completedStreams: number;
    cancelledStreams: number;
    totalDeposits: Record<string, string>;
    totalDistributed: Record<string, string>;
    totalRecipients: number;
  }
): jsPDF {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Add header to first page
  addHeader(doc, "Streams Analytics Report", "Comprehensive stream data and analytics");

  let yPos = PDF_CONFIG.headerHeight + 15;

  // Add summary section if provided
  if (summaryStats) {
    yPos = addSummarySection(doc, summaryStats);
  }

  // Add streams summary table
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PDF_CONFIG.textColor[0], PDF_CONFIG.textColor[1], PDF_CONFIG.textColor[2]);
  doc.text("All Streams Summary", PDF_CONFIG.pageMargin, yPos);
  yPos += 8;

  yPos = addStreamsSummaryTable(doc, allStreamsData, yPos);

  // Add detailed stream information
  if (allStreamsData.length <= 5) {
    // Only add detailed info if we have 5 or fewer streams
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Detailed Stream Information", PDF_CONFIG.pageMargin, yPos);
    yPos += 10;

    allStreamsData.forEach((streamData) => {
      yPos = addStreamDetails(doc, streamData, yPos);
    });
  }

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  return doc;
}

/**
 * Download PDF
 */
export function downloadPDF(doc: jsPDF, filename: string): void {
  const fullFilename = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
  doc.save(fullFilename);
}

